name: publish Docker

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ouily1/postgres-ghcr:latest 

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            docker login --username ouily1 --password ${{ secrets.GH_PAT }} ghcr.io
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
      needs: publish
      name: deploy image
      runs-on: ubuntu-latest

      env:
       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       SSH_HOST: ${{ secrets.SSH_HOST }}

      steps:
       - name: install ssh keys
         run: |
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
       - name: connect and pull
         run: |
           ssh -o StrictHostKeyChecking=no root@192.168.1.28 "cd ${{ secrets.WORK_DIR }} && docker-compose up -d && exit"
