name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ouily1/postgres-ghcr:latest 

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            docker login --username ouily1 --password ${{ secrets.GH_PAT }} ghcr.io
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Create SSH key
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ../private.key
            sudo chmod 600 ../private.key
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          shell: bash
          env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
            SSH_KEY_PATH: ${{ github.workspace }}/../private.key
        - name: SSH into Server and Run Commands
          run: |
            ssh -i $SSH_KEY_PATH ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name test -p 5460/5432 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          env:
            SSH_KEY_PATH: ${{ github.workspace }}/../private.key
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
           
