name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ouily1/postgres-ghcr:latest 

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            docker login --username ouily1 --password ${{ secrets.GH_PAT }} ghcr.io
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: publish
        name: deploy image
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
          run: |
            which ssh-agent || (sudo apk update && sudo apk add openssh-client)
            which rsync || (sudo apk update && sudo apk add rsync)
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/private.key
            touch ~/.ssh/known_hosts
            chmod 600 ~/.ssh/private.key
            echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/private.key
            # Append keyscan output into known hosts
            ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name test -p 5432:5432 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        - name: cleanup
          run: rm -rf ~/.ssh
